import { AuthorAffiliation } from './author-affiliation';
import { Center } from './center';
import { Copyright } from './copyright';
import { Cui } from './cui';
import { Download } from './download';
import { ExportControl } from './export-control';
import { FundingNumber } from './funding-number';
import { LegacyMeta } from './legacy-meta';
import { Meeting } from './meeting';
import { Publication } from './publication';
import { RelatedCitation } from './related-citation';
import { SourceIdentifier } from './source-identifier';

export interface Citation {
    status: string;
    stiType: string;
    technicalReviewType: string;
    onlyAbstract: boolean;
    isLessonsLearned: boolean;
    disseminated: string;
    distribution: string;
    id: number;
    index: string;
    stiTypeDetails: string;
    title: string;
    abstract: string;
    authorAffiliations: AuthorAffiliation;
    center: Center;
    publications: Publication;
    meetings: Meeting;
    distributionDate: string;
    copyright: Copyright;
    exportControl: ExportControl;
    sensitiveInformation: string;
    cui: Cui;
    fundingNumbers: FundingNumber;
    otherReportNumbers: string;
    sourceIdentifiers: SourceIdentifier;
    subjectCategories: string;
    keywords: string;
    created: string;
    modified: string;
    submittedDate: string;
    curatedDate: string;
    redistributedDate: string;
    downloadsAvailable: boolean;
    downloads: Download;
    related: RelatedCitation;
    legacyMeta: LegacyMeta;
}