export enum Distribution {
    PUBLIC, 
    US_PERSONS, 
    US_GOVERNMENT_AGENCIES_AND_GOVERNMENT_AGENCY_CONTRACTORS, 
    US_GOVERNMENT_AGENCIES, 
    US_GOVERNMENT_AGENCIES_AND_NASA_CONTRACTORS, 
    NASA_CIVIL_SERVANTS_AND_NASA_CONTRACTORS, 
    NASA_CIVIL_SERVANTS, 
    OFFICE_ONLY, 
    DO_NOT_DISTRIBUTE
}